Repository riak-core-lite/riak_core_lite, pull requests merged in 2020-09, with the labels that each got.

#68 Update riak_core_vnode API
  src/riak_core_handoff_receiver.erl
  src/riak_core_handoff_sender.erl
  src/riak_core_vnode.erl
  src/riak_core_vnode_manager.erl
  src/riak_core_vnode_master.erl
  src/riak_core_vnode_proxy.erl
Labels: architecture, enhancement

#71 Fixed #70
  src/riak_core_vnode_proxy.erl
Labels: bug, testing

#72 Fix Proper License Issue
  Makefile
  rebar.config
Labels: Community

#75 Finish removing bucket properties and buckets
  src/gen_fsm_compat.erl
  src/gen_nb_server.erl
  src/riak_core.app.src
  src/riak_core.erl
  src/riak_core_apl.erl
  src/riak_core_bucket.erl
  src/riak_core_bucket_props.erl
  src/riak_core_claim.erl
  src/riak_core_claimant.erl
  src/riak_core_gossip.erl
  src/riak_core_handoff_manager.erl
  src/riak_core_handoff_receiver.erl
  src/riak_core_node_watcher.erl
  src/riak_core_rand.erl
  src/riak_core_ring.erl
  src/riak_core_ring_handler.erl
  src/riak_core_ring_manager.erl
  src/riak_core_ring_util.erl
  src/riak_core_send_msg.erl
  src/riak_core_util.erl
  src/riak_core_vnode.erl
  src/riak_core_vnode_manager.erl
  src/riak_core_vnode_master.erl
  src/riak_core_vnode_proxy.erl
  src/riak_core_vnode_worker.erl
  test/pqc/bprops_eqc.erl
  test/pqc/bucket_eqc_utils.erl
Labels: deprecated, reduce
